import Header from "@/Components/Common/Header/Header";
import "./globals.css";
import Footer from "@/Components/Common/Footer.jsx/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
